spring:
  profiles:
    group:
      "local": "localDB, devPort, secret, web-mvc"
      "dev": "devDB, devPort, secret, web-mvc"
      "prod": "prodDB, prodPort, secret, web-mvc"

---

oauth:
  apple:
    iss: "https://appleid.apple.com"
    client-id: ${OAUTH_APPLE_CLIENT_ID} # Apple Developers CoNet Bundle ID
    nonce: ${OAUTH_APPLE_NONCE}
  kakao:
    iss: "https://kauth.kakao.com"
    client-id: ${OAUTH_KAKAO_CLIENT_ID} # Kakao Developers CoNet REST API Key

---

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    stack.auto: false
    region:
      static: ap-northeast-2
      auto: false
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}

---

spring:
  config:
    activate:
      on-profile: "localDB" # MySQL ver 8
  datasource:
    url: ${DATASOURCE_URL_LOCAL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1
  sql:
    init:
      platform: mysql
  data:
    redis:
      host: ${DATA_REDIS_HOST}
      port: ${DATA_REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  log:
    config:
      path: ./logs
      filename: app-local
      maxHistory: 3 # 3일
      totalSizeCap: 10MB # 로그 파일 사이즈

---

spring:
  config:
    activate:
      on-profile: "devDB"

  datasource:
    url: ${DATASOURCE_URL_DEV}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1
  sql:
    init:
      platform: mysql
  data:
    redis:
      host: ${DATA_REDIS_HOST}
      port: ${DATA_REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: update #create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  log:
    config:
      path: ./logs
      filename: app-dev
      maxHistory: 7 # 7일
      totalSizeCap: 1GB # 로그 파일 사이즈

---

spring:
  config:
    activate:
      on-profile: "prodDB"

  datasource:
    url: ${DATASOURCE_URL_PROD}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1
  sql:
    init:
      platform: mysql

  data:
    redis:
      host: ${DATA_REDIS_HOST}
      port: ${DATA_REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  log:
    config:
      path: ./logs
      filename: app-prod
      maxHistory: 10 # 10일
      totalSizeCap: 1GB # 로그 파일 사이즈

---

spring:
  config:
    activate:
      on-profile: "devPort"

server:
  port: 9000

---

spring:
  config:
    activate:
      on-profile: "prodPort"

server:
  port: 9001

---

spring:
  config:
    activate:
      on-profile: "secret"

secret:
  jwt-secret-key: ${JWT_SECRET_KEY}
  jwt-expired-in: ${JWT_EXPIRED_IN}

---

spring:
  config:
    activate:
      on-profile: "web-mvc"

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  messages:
    basename: errors
